services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - 'pg_data:/bitnami/postgresql'
      - './docker:/docker-entrypoint-initdb.d'

volumes:
  pg_data:
